### ISSUE TITLE
Add license file called: LICENSE.md

### ISSUE THREAD

**Issue by Eiji7** [jeffdeville/nhverify#13]
We should describe how we license this project.
As other github projects we should provide **LICENSE.md** file.

**Comment by jeffdeville** [comment]
This code is going to wind up being private. I opened it to the public because I'd received so much interest on ElixirForums, and it was easier to do this than give each individual access. But I'm investing a lot of money in this, and there's anyone who would be using it would pretty much have to be competing with me.

**Comment by Eiji7** [comment]
> This code is going to wind up being private.

oh no problem, but what about docs?
From `README.md`:
> If available in Hex

From beginner it looks like as an Open Source project.
Maybe I just badly understood it, but in this case we should change this file, right?

btw. I don't know if it's possible to publish docs on hex for private project. In docs there are links to code, so I was think that it's not possible. So in this case `if available on hex` always will `return false` :smile:
