### ISSUE TITLE
Changes in Licensee model

### ISSUE THREAD

**Issue by Eiji7** [jeffdeville/nhverify#8]
- [x] change `:phone` field to `:phones` (multiple phones)
- [ ] change `:notes` field from `:text`, to: `{:array, :string}` (or `{:array, :text}` - i don't see `:text` in docs), so we can simply save multiple notes (as name already say) without special formatting
- [x] add `:faxes` field - like `:phones`
- [x] move: `:full_text_address`, `:addr1`, `:addr2`, `:city`, `:region`, `:postal_code`, `:phones` and `:faxes` to separate model Contact with relation **belongs_to** `:licensee` - Licensee will have relation **has_many** to `:contacts`
- [ ] use [ecto_enum](https://github.com/gjaldon/ecto_enum) for `:license_status` field
- [x] update already created scrapers to work with this changes

**Comment by jeffdeville** [comment]
Let's hold off of ecto_enum for now, because I don't know what all of the valid statuses are going to be yet. So for now, it's easier to just shovel them into the tables as text. If we need something other than 'Active', we can come back to this. But I don't want to force the scrapers to map status values we don't care about. It's just more code to have to maintain.

**Comment by Eiji7** [comment]
@jeffdeville: no problem, I just want to point all changes that should be done which I can see
